// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: training.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Model_CreateModel_FullMethodName        = "/training.Model/create_model"
	Model_ValidateModelPrice_FullMethodName = "/training.Model/validate_model_price"
	Model_UploadAndValidate_FullMethodName  = "/training.Model/upload_and_validate"
	Model_ValidateModel_FullMethodName      = "/training.Model/validate_model"
	Model_TrainModelPrice_FullMethodName    = "/training.Model/train_model_price"
	Model_TrainModel_FullMethodName         = "/training.Model/train_model"
	Model_DeleteModel_FullMethodName        = "/training.Model/delete_model"
	Model_GetModelStatus_FullMethodName     = "/training.Model/get_model_status"
)

// ModelClient is the client API for Model service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Methods that the service provider must implement
type ModelClient interface {
	// Free
	// Can pass the address of the model creator
	CreateModel(ctx context.Context, in *NewModel, opts ...grpc.CallOption) (*ModelID, error)
	// Free
	ValidateModelPrice(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*PriceInBaseUnit, error)
	// Paid
	UploadAndValidate(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadInput, StatusResponse], error)
	// Paid
	ValidateModel(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Free, one signature for both train_model_price & train_model methods
	TrainModelPrice(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*PriceInBaseUnit, error)
	// Paid
	TrainModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*StatusResponse, error)
	// Free
	DeleteModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*StatusResponse, error)
	// Free
	GetModelStatus(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*StatusResponse, error)
}

type modelClient struct {
	cc grpc.ClientConnInterface
}

func NewModelClient(cc grpc.ClientConnInterface) ModelClient {
	return &modelClient{cc}
}

func (c *modelClient) CreateModel(ctx context.Context, in *NewModel, opts ...grpc.CallOption) (*ModelID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelID)
	err := c.cc.Invoke(ctx, Model_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) ValidateModelPrice(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*PriceInBaseUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceInBaseUnit)
	err := c.cc.Invoke(ctx, Model_ValidateModelPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) UploadAndValidate(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadInput, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Model_ServiceDesc.Streams[0], Model_UploadAndValidate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadInput, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Model_UploadAndValidateClient = grpc.ClientStreamingClient[UploadInput, StatusResponse]

func (c *modelClient) ValidateModel(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Model_ValidateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) TrainModelPrice(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*PriceInBaseUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceInBaseUnit)
	err := c.cc.Invoke(ctx, Model_TrainModelPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) TrainModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Model_TrainModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) DeleteModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Model_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) GetModelStatus(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Model_GetModelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServer is the server API for Model service.
// All implementations must embed UnimplementedModelServer
// for forward compatibility.
//
// Methods that the service provider must implement
type ModelServer interface {
	// Free
	// Can pass the address of the model creator
	CreateModel(context.Context, *NewModel) (*ModelID, error)
	// Free
	ValidateModelPrice(context.Context, *ValidateRequest) (*PriceInBaseUnit, error)
	// Paid
	UploadAndValidate(grpc.ClientStreamingServer[UploadInput, StatusResponse]) error
	// Paid
	ValidateModel(context.Context, *ValidateRequest) (*StatusResponse, error)
	// Free, one signature for both train_model_price & train_model methods
	TrainModelPrice(context.Context, *ModelID) (*PriceInBaseUnit, error)
	// Paid
	TrainModel(context.Context, *ModelID) (*StatusResponse, error)
	// Free
	DeleteModel(context.Context, *ModelID) (*StatusResponse, error)
	// Free
	GetModelStatus(context.Context, *ModelID) (*StatusResponse, error)
	mustEmbedUnimplementedModelServer()
}

// UnimplementedModelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServer struct{}

func (UnimplementedModelServer) CreateModel(context.Context, *NewModel) (*ModelID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedModelServer) ValidateModelPrice(context.Context, *ValidateRequest) (*PriceInBaseUnit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateModelPrice not implemented")
}
func (UnimplementedModelServer) UploadAndValidate(grpc.ClientStreamingServer[UploadInput, StatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadAndValidate not implemented")
}
func (UnimplementedModelServer) ValidateModel(context.Context, *ValidateRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateModel not implemented")
}
func (UnimplementedModelServer) TrainModelPrice(context.Context, *ModelID) (*PriceInBaseUnit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainModelPrice not implemented")
}
func (UnimplementedModelServer) TrainModel(context.Context, *ModelID) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainModel not implemented")
}
func (UnimplementedModelServer) DeleteModel(context.Context, *ModelID) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedModelServer) GetModelStatus(context.Context, *ModelID) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelStatus not implemented")
}
func (UnimplementedModelServer) mustEmbedUnimplementedModelServer() {}
func (UnimplementedModelServer) testEmbeddedByValue()               {}

// UnsafeModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServer will
// result in compilation errors.
type UnsafeModelServer interface {
	mustEmbedUnimplementedModelServer()
}

func RegisterModelServer(s grpc.ServiceRegistrar, srv ModelServer) {
	// If the following call pancis, it indicates UnimplementedModelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Model_ServiceDesc, srv)
}

func _Model_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).CreateModel(ctx, req.(*NewModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_ValidateModelPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ValidateModelPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_ValidateModelPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ValidateModelPrice(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_UploadAndValidate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModelServer).UploadAndValidate(&grpc.GenericServerStream[UploadInput, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Model_UploadAndValidateServer = grpc.ClientStreamingServer[UploadInput, StatusResponse]

func _Model_ValidateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ValidateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_ValidateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ValidateModel(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_TrainModelPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).TrainModelPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_TrainModelPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).TrainModelPrice(ctx, req.(*ModelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_TrainModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).TrainModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_TrainModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).TrainModel(ctx, req.(*ModelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).DeleteModel(ctx, req.(*ModelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_GetModelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).GetModelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Model_GetModelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).GetModelStatus(ctx, req.(*ModelID))
	}
	return interceptor(ctx, in, info, handler)
}

// Model_ServiceDesc is the grpc.ServiceDesc for Model service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Model_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "training.Model",
	HandlerType: (*ModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create_model",
			Handler:    _Model_CreateModel_Handler,
		},
		{
			MethodName: "validate_model_price",
			Handler:    _Model_ValidateModelPrice_Handler,
		},
		{
			MethodName: "validate_model",
			Handler:    _Model_ValidateModel_Handler,
		},
		{
			MethodName: "train_model_price",
			Handler:    _Model_TrainModelPrice_Handler,
		},
		{
			MethodName: "train_model",
			Handler:    _Model_TrainModel_Handler,
		},
		{
			MethodName: "delete_model",
			Handler:    _Model_DeleteModel_Handler,
		},
		{
			MethodName: "get_model_status",
			Handler:    _Model_GetModelStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "upload_and_validate",
			Handler:       _Model_UploadAndValidate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "training.proto",
}
