// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: training.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_CREATED      Status = 0
	Status_VALIDATING   Status = 1
	Status_VALIDATED    Status = 2
	Status_TRAINING     Status = 3
	Status_READY_TO_USE Status = 4 // After training is completed
	Status_ERRORED      Status = 5
	Status_DELETED      Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "CREATED",
		1: "VALIDATING",
		2: "VALIDATED",
		3: "TRAINING",
		4: "READY_TO_USE",
		5: "ERRORED",
		6: "DELETED",
	}
	Status_value = map[string]int32{
		"CREATED":      0,
		"VALIDATING":   1,
		"VALIDATED":    2,
		"TRAINING":     3,
		"READY_TO_USE": 4,
		"ERRORED":      5,
		"DELETED":      6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_training_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_training_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{0}
}

type ModelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelId         string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Status          Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=training.Status" json:"status,omitempty"`
	CreatedDate     string                 `protobuf:"bytes,3,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate     string                 `protobuf:"bytes,4,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	GrpcMethodName  string                 `protobuf:"bytes,7,opt,name=grpc_method_name,json=grpcMethodName,proto3" json:"grpc_method_name,omitempty"`
	GrpcServiceName string                 `protobuf:"bytes,8,opt,name=grpc_service_name,json=grpcServiceName,proto3" json:"grpc_service_name,omitempty"`
	// List of all addresses that will have access to this model
	AddressList []string `protobuf:"bytes,9,rep,name=address_list,json=addressList,proto3" json:"address_list,omitempty"`
	// Access to the model is granted only for use and viewing
	IsPublic         bool   `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	TrainingDataLink string `protobuf:"bytes,11,opt,name=training_data_link,json=trainingDataLink,proto3" json:"training_data_link,omitempty"`
	CreatedByAddress string `protobuf:"bytes,12,opt,name=created_by_address,json=createdByAddress,proto3" json:"created_by_address,omitempty"`
	UpdatedByAddress string `protobuf:"bytes,13,opt,name=updated_by_address,json=updatedByAddress,proto3" json:"updated_by_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelResponse) Reset() {
	*x = ModelResponse{}
	mi := &file_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponse) ProtoMessage() {}

func (x *ModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResponse.ProtoReflect.Descriptor instead.
func (*ModelResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{0}
}

func (x *ModelResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

func (x *ModelResponse) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *ModelResponse) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *ModelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelResponse) GetGrpcMethodName() string {
	if x != nil {
		return x.GrpcMethodName
	}
	return ""
}

func (x *ModelResponse) GetGrpcServiceName() string {
	if x != nil {
		return x.GrpcServiceName
	}
	return ""
}

func (x *ModelResponse) GetAddressList() []string {
	if x != nil {
		return x.AddressList
	}
	return nil
}

func (x *ModelResponse) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ModelResponse) GetTrainingDataLink() string {
	if x != nil {
		return x.TrainingDataLink
	}
	return ""
}

func (x *ModelResponse) GetCreatedByAddress() string {
	if x != nil {
		return x.CreatedByAddress
	}
	return ""
}

func (x *ModelResponse) GetUpdatedByAddress() string {
	if x != nil {
		return x.UpdatedByAddress
	}
	return ""
}

// Used as input for new_model requests
// The service provider decides whether to use these fields; returning model_id is mandatory
type NewModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	GrpcMethodName  string                 `protobuf:"bytes,3,opt,name=grpc_method_name,json=grpcMethodName,proto3" json:"grpc_method_name,omitempty"`
	GrpcServiceName string                 `protobuf:"bytes,4,opt,name=grpc_service_name,json=grpcServiceName,proto3" json:"grpc_service_name,omitempty"`
	// List of all addresses that will have access to this model
	AddressList []string `protobuf:"bytes,5,rep,name=address_list,json=addressList,proto3" json:"address_list,omitempty"`
	// Set this to true if you want your model to be accessible by other AI consumers
	IsPublic bool `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	// These parameters will be passed by the daemon
	OrganizationId string `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ServiceId      string `protobuf:"bytes,8,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	GroupId        string `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewModel) Reset() {
	*x = NewModel{}
	mi := &file_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewModel) ProtoMessage() {}

func (x *NewModel) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewModel.ProtoReflect.Descriptor instead.
func (*NewModel) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{1}
}

func (x *NewModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewModel) GetGrpcMethodName() string {
	if x != nil {
		return x.GrpcMethodName
	}
	return ""
}

func (x *NewModel) GetGrpcServiceName() string {
	if x != nil {
		return x.GrpcServiceName
	}
	return ""
}

func (x *NewModel) GetAddressList() []string {
	if x != nil {
		return x.AddressList
	}
	return nil
}

func (x *NewModel) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *NewModel) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *NewModel) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *NewModel) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// This structure must be used by the service provider
type ModelID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelID) Reset() {
	*x = ModelID{}
	mi := &file_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelID) ProtoMessage() {}

func (x *ModelID) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelID.ProtoReflect.Descriptor instead.
func (*ModelID) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{2}
}

func (x *ModelID) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// This structure must be used by the service provider
// Used in the train_model_price method to get the training/validation price
type PriceInBaseUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         uint64                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"` // cogs, weis, afet, aasi, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceInBaseUnit) Reset() {
	*x = PriceInBaseUnit{}
	mi := &file_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceInBaseUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceInBaseUnit) ProtoMessage() {}

func (x *PriceInBaseUnit) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceInBaseUnit.ProtoReflect.Descriptor instead.
func (*PriceInBaseUnit) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{3}
}

func (x *PriceInBaseUnit) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=training.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

type UploadInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      uint64                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // in bytes
	BatchSize     uint64                 `protobuf:"varint,5,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchNumber   uint64                 `protobuf:"varint,6,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	BatchCount    uint64                 `protobuf:"varint,7,opt,name=batch_count,json=batchCount,proto3" json:"batch_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInput) Reset() {
	*x = UploadInput{}
	mi := &file_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInput) ProtoMessage() {}

func (x *UploadInput) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInput.ProtoReflect.Descriptor instead.
func (*UploadInput) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{5}
}

func (x *UploadInput) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *UploadInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadInput) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadInput) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *UploadInput) GetBatchNumber() uint64 {
	if x != nil {
		return x.BatchNumber
	}
	return 0
}

func (x *UploadInput) GetBatchCount() uint64 {
	if x != nil {
		return x.BatchCount
	}
	return 0
}

type ValidateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelId          string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	TrainingDataLink string                 `protobuf:"bytes,3,opt,name=training_data_link,json=trainingDataLink,proto3" json:"training_data_link,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_training_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ValidateRequest) GetTrainingDataLink() string {
	if x != nil {
		return x.TrainingDataLink
	}
	return ""
}

var file_training_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "training.default_model_id",
		Tag:           "bytes,50001,opt,name=default_model_id",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint64)(nil),
		Field:         50002,
		Name:          "training.max_models_per_user",
		Tag:           "varint,50002,opt,name=max_models_per_user",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint64)(nil),
		Field:         50003,
		Name:          "training.dataset_max_size_mb",
		Tag:           "varint,50003,opt,name=dataset_max_size_mb",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint64)(nil),
		Field:         50004,
		Name:          "training.dataset_max_count_files",
		Tag:           "varint,50004,opt,name=dataset_max_count_files",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint64)(nil),
		Field:         50005,
		Name:          "training.dataset_max_size_single_file_mb",
		Tag:           "varint,50005,opt,name=dataset_max_size_single_file_mb",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50006,
		Name:          "training.dataset_files_type",
		Tag:           "bytes,50006,opt,name=dataset_files_type",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50007,
		Name:          "training.dataset_type",
		Tag:           "bytes,50007,opt,name=dataset_type",
		Filename:      "training.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50008,
		Name:          "training.dataset_description",
		Tag:           "bytes,50008,opt,name=dataset_description",
		Filename:      "training.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string default_model_id = 50001;
	E_DefaultModelId = &file_training_proto_extTypes[0]
	// optional uint64 max_models_per_user = 50002;
	E_MaxModelsPerUser = &file_training_proto_extTypes[1] // max models per method & user
	// optional uint64 dataset_max_size_mb = 50003;
	E_DatasetMaxSizeMb = &file_training_proto_extTypes[2] // max size of dataset
	// optional uint64 dataset_max_count_files = 50004;
	E_DatasetMaxCountFiles = &file_training_proto_extTypes[3] // maximum number of files in the dataset
	// optional uint64 dataset_max_size_single_file_mb = 50005;
	E_DatasetMaxSizeSingleFileMb = &file_training_proto_extTypes[4] // maximum size of a single file in the dataset
	// optional string dataset_files_type = 50006;
	E_DatasetFilesType = &file_training_proto_extTypes[5] // allowed files types in dataset. string with array or single value, example: jpg, png, mp3
	// optional string dataset_type = 50007;
	E_DatasetType = &file_training_proto_extTypes[6] // string with array or single value, example: zip, tar.gz, tar
	// optional string dataset_description = 50008;
	E_DatasetDescription = &file_training_proto_extTypes[7] // additional free-form requirements
)

var File_training_proto protoreflect.FileDescriptor

const file_training_proto_rawDesc = "" +
	"\n" +
	"\x0etraining.proto\x12\btraining\x1a google/protobuf/descriptor.proto\"\xf0\x03\n" +
	"\rModelResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.training.StatusR\x06status\x12!\n" +
	"\fcreated_date\x18\x03 \x01(\tR\vcreatedDate\x12!\n" +
	"\fupdated_date\x18\x04 \x01(\tR\vupdatedDate\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12(\n" +
	"\x10grpc_method_name\x18\a \x01(\tR\x0egrpcMethodName\x12*\n" +
	"\x11grpc_service_name\x18\b \x01(\tR\x0fgrpcServiceName\x12!\n" +
	"\faddress_list\x18\t \x03(\tR\vaddressList\x12\x1b\n" +
	"\tis_public\x18\n" +
	" \x01(\bR\bisPublic\x12,\n" +
	"\x12training_data_link\x18\v \x01(\tR\x10trainingDataLink\x12,\n" +
	"\x12created_by_address\x18\f \x01(\tR\x10createdByAddress\x12,\n" +
	"\x12updated_by_address\x18\r \x01(\tR\x10updatedByAddress\"\xb9\x02\n" +
	"\bNewModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x10grpc_method_name\x18\x03 \x01(\tR\x0egrpcMethodName\x12*\n" +
	"\x11grpc_service_name\x18\x04 \x01(\tR\x0fgrpcServiceName\x12!\n" +
	"\faddress_list\x18\x05 \x03(\tR\vaddressList\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"service_id\x18\b \x01(\tR\tserviceId\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\"$\n" +
	"\aModelID\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"'\n" +
	"\x0fPriceInBaseUnit\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x04R\x05price\":\n" +
	"\x0eStatusResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.training.StatusR\x06status\"\xd9\x01\n" +
	"\vUploadInput\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x04R\bfileSize\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x05 \x01(\x04R\tbatchSize\x12!\n" +
	"\fbatch_number\x18\x06 \x01(\x04R\vbatchNumber\x12\x1f\n" +
	"\vbatch_count\x18\a \x01(\x04R\n" +
	"batchCount\"Z\n" +
	"\x0fValidateRequest\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12,\n" +
	"\x12training_data_link\x18\x03 \x01(\tR\x10trainingDataLink*n\n" +
	"\x06Status\x12\v\n" +
	"\aCREATED\x10\x00\x12\x0e\n" +
	"\n" +
	"VALIDATING\x10\x01\x12\r\n" +
	"\tVALIDATED\x10\x02\x12\f\n" +
	"\bTRAINING\x10\x03\x12\x10\n" +
	"\fREADY_TO_USE\x10\x04\x12\v\n" +
	"\aERRORED\x10\x05\x12\v\n" +
	"\aDELETED\x10\x062\xaa\x04\n" +
	"\x05Model\x127\n" +
	"\fcreate_model\x12\x12.training.NewModel\x1a\x11.training.ModelID\"\x00\x12N\n" +
	"\x14validate_model_price\x12\x19.training.ValidateRequest\x1a\x19.training.PriceInBaseUnit\"\x00\x12J\n" +
	"\x13upload_and_validate\x12\x15.training.UploadInput\x1a\x18.training.StatusResponse\"\x00(\x01\x12G\n" +
	"\x0evalidate_model\x12\x19.training.ValidateRequest\x1a\x18.training.StatusResponse\"\x00\x12C\n" +
	"\x11train_model_price\x12\x11.training.ModelID\x1a\x19.training.PriceInBaseUnit\"\x00\x12<\n" +
	"\vtrain_model\x12\x11.training.ModelID\x1a\x18.training.StatusResponse\"\x00\x12=\n" +
	"\fdelete_model\x12\x11.training.ModelID\x1a\x18.training.StatusResponse\"\x00\x12A\n" +
	"\x10get_model_status\x12\x11.training.ModelID\x1a\x18.training.StatusResponse\"\x00:J\n" +
	"\x10default_model_id\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x0edefaultModelId:O\n" +
	"\x13max_models_per_user\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\x04R\x10maxModelsPerUser:O\n" +
	"\x13dataset_max_size_mb\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\x04R\x10datasetMaxSizeMb:W\n" +
	"\x17dataset_max_count_files\x12\x1e.google.protobuf.MethodOptions\x18Ԇ\x03 \x01(\x04R\x14datasetMaxCountFiles:e\n" +
	"\x1fdataset_max_size_single_file_mb\x12\x1e.google.protobuf.MethodOptions\x18Ն\x03 \x01(\x04R\x1adatasetMaxSizeSingleFileMb:N\n" +
	"\x12dataset_files_type\x12\x1e.google.protobuf.MethodOptions\x18ֆ\x03 \x01(\tR\x10datasetFilesType:C\n" +
	"\fdataset_type\x12\x1e.google.protobuf.MethodOptions\x18׆\x03 \x01(\tR\vdatasetType:Q\n" +
	"\x13dataset_description\x12\x1e.google.protobuf.MethodOptions\x18؆\x03 \x01(\tR\x12datasetDescriptionB\fZ\n" +
	"../serviceb\x06proto3"

var (
	file_training_proto_rawDescOnce sync.Once
	file_training_proto_rawDescData []byte
)

func file_training_proto_rawDescGZIP() []byte {
	file_training_proto_rawDescOnce.Do(func() {
		file_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_proto_rawDesc), len(file_training_proto_rawDesc)))
	})
	return file_training_proto_rawDescData
}

var file_training_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_training_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_training_proto_goTypes = []any{
	(Status)(0),                        // 0: training.Status
	(*ModelResponse)(nil),              // 1: training.ModelResponse
	(*NewModel)(nil),                   // 2: training.NewModel
	(*ModelID)(nil),                    // 3: training.ModelID
	(*PriceInBaseUnit)(nil),            // 4: training.PriceInBaseUnit
	(*StatusResponse)(nil),             // 5: training.StatusResponse
	(*UploadInput)(nil),                // 6: training.UploadInput
	(*ValidateRequest)(nil),            // 7: training.ValidateRequest
	(*descriptorpb.MethodOptions)(nil), // 8: google.protobuf.MethodOptions
}
var file_training_proto_depIdxs = []int32{
	0,  // 0: training.ModelResponse.status:type_name -> training.Status
	0,  // 1: training.StatusResponse.status:type_name -> training.Status
	8,  // 2: training.default_model_id:extendee -> google.protobuf.MethodOptions
	8,  // 3: training.max_models_per_user:extendee -> google.protobuf.MethodOptions
	8,  // 4: training.dataset_max_size_mb:extendee -> google.protobuf.MethodOptions
	8,  // 5: training.dataset_max_count_files:extendee -> google.protobuf.MethodOptions
	8,  // 6: training.dataset_max_size_single_file_mb:extendee -> google.protobuf.MethodOptions
	8,  // 7: training.dataset_files_type:extendee -> google.protobuf.MethodOptions
	8,  // 8: training.dataset_type:extendee -> google.protobuf.MethodOptions
	8,  // 9: training.dataset_description:extendee -> google.protobuf.MethodOptions
	2,  // 10: training.Model.create_model:input_type -> training.NewModel
	7,  // 11: training.Model.validate_model_price:input_type -> training.ValidateRequest
	6,  // 12: training.Model.upload_and_validate:input_type -> training.UploadInput
	7,  // 13: training.Model.validate_model:input_type -> training.ValidateRequest
	3,  // 14: training.Model.train_model_price:input_type -> training.ModelID
	3,  // 15: training.Model.train_model:input_type -> training.ModelID
	3,  // 16: training.Model.delete_model:input_type -> training.ModelID
	3,  // 17: training.Model.get_model_status:input_type -> training.ModelID
	3,  // 18: training.Model.create_model:output_type -> training.ModelID
	4,  // 19: training.Model.validate_model_price:output_type -> training.PriceInBaseUnit
	5,  // 20: training.Model.upload_and_validate:output_type -> training.StatusResponse
	5,  // 21: training.Model.validate_model:output_type -> training.StatusResponse
	4,  // 22: training.Model.train_model_price:output_type -> training.PriceInBaseUnit
	5,  // 23: training.Model.train_model:output_type -> training.StatusResponse
	5,  // 24: training.Model.delete_model:output_type -> training.StatusResponse
	5,  // 25: training.Model.get_model_status:output_type -> training.StatusResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	2,  // [2:10] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_training_proto_init() }
func file_training_proto_init() {
	if File_training_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_proto_rawDesc), len(file_training_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 8,
			NumServices:   1,
		},
		GoTypes:           file_training_proto_goTypes,
		DependencyIndexes: file_training_proto_depIdxs,
		EnumInfos:         file_training_proto_enumTypes,
		MessageInfos:      file_training_proto_msgTypes,
		ExtensionInfos:    file_training_proto_extTypes,
	}.Build()
	File_training_proto = out.File
	file_training_proto_goTypes = nil
	file_training_proto_depIdxs = nil
}
